services:
  - type: web
    name: online-shop
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash deploy/start.sh
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: BOT_WEBHOOK_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
